# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c753417d89a016a19559beaec9f38a5a61f5ab7ad412f51971f902352b5667c559bf99b5f126ef9f4a23e230907416c9863bd16f491931e1f201d807c3ee651c
  stripe_api_key: <%= ENV["SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["PUBLISHABLE_KEY"] %>
test:
  secret_key_base: f27bd95ab3c42ada005d38a65b5bef1cc6044f95d83cb4bfecb6b238480ebf4abd389e75d0ae40e12602963555c952ed251e2f51290d8c9ef6eee43bb8f45fc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_api_key: <%= ENV["SECRET_KEY"] %>
  stripe_publishable_key: <%= ENV["PUBLISHABLE_KEY"] %>
